# Generated by Django 3.0 on 2019-12-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_auto_20191222_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='storage_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('parent', 'name')},
        ),
    ]
