# Generated by Django 3.0 on 2019-12-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_auto_20191222_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='storage_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
