# Generated by Django 3.0 on 2019-12-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_auto_20191222_2215'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('directory', 'name')},
        ),
    ]
